version: '3.7'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'mdservice_1'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '2137272lolwow'
      MYSQL_ROOT_PASSWORD: '2137272lolwow'
    ports:
    - "3306:3306"
    networks:
    - default

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    environment:
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest
    ports:
    - "5672:5672"
    - "15672:15672"
    networks:
    - default

  configs:
    container_name: configs
    build:
      context: ./configs
      dockerfile: Dockerfile
    ports:
    - "8088:8088"
    networks:
    - default

    feign-service:
      container_name: feign-service
      depends_on:
      - configs
      - rabbitmq
      build:
        context: ./feign-service
        dockerfile: Dockerfile
      ports:
      - "8095:8095"
      networks:
      - default

  service-registry:
    depends_on:
    - configs
    container_name: service-registry
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    ports:
    - "8063:8063"
    networks:
    - default

  services:
    depends_on:
    - configs
    - service-registry
    - rabbitmq
    - mysqldb
    container_name: services
    build:
      context: ./services
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    networks:
    - default
